### PR TITLE
Issue34 edit post action

### PR DESCRIPTION
**Pull request by JarodXP**
Hi Wyona,

This is the pull request for the editPostAction().

Please review and merge if it's ok.

### CODE REVIEW

**Comment by Tutt-J** [comment]
Hi,

Please comment your code else i take too long time to understand what you do.

**Comment by JarodXP** [comment]
ok, comments added on AdminBlogController.php

**Comment by Tutt-J** [comment]
Thx.

Why use this :

             ```
   'app' => 'back',
                'userRegistered' => true
```

It should be global variables

**Comment by JarodXP** [comment]
ok done, app variable was already set as global, I forgot to delete it.
userRegistered was just to be use meanwhile User class is not created

**Comment by Tutt-J** [comment]
Okay you can merge it

**Pull request merged**
